### ISSUE TITLE
Tepid-refine, merge_insertions.py

### ISSUE THREAD

**Issue by Caro-Ca** [ListerLab/TEPID#16]
Hi! 
I'm trying to get the file containing all identified variants in groups so as to run Tepid-refine, but I got an error while running the merge_insertions.py script: 

```
python ~/TEPID/Scripts/merge_insertions.py -f refined_insertions
Traceback (most recent call last):
  File "/home/silviav/TEPID/Scripts/merge_insertions.py", line 129, in <module>
    main(options.filename)
  File "/home/silviav/TEPID/Scripts/merge_insertions.py", line 112, in main
    for key, value in master_insertions.iteritems():
UnboundLocalError: local variable 'master_insertions' referenced before assignment 
```

Could you tell me what is missing? 
Thank you in advance for your help.

**Comment by Morriyaty** [comment]
Hi. Had you fixed this error ? I got the same one.

**Comment by yuejian1** [comment]
merge_insertions.py -f insertions

**Comment by altingia** [comment]
both the merge_deletions.py and merge_insertions.py works for specific input arrangements, for instance, there are 'A', 'B', 'C'  folders under current directory Population1,  in each directory, there were outputs of Tepid-discoverty . such as 'deletions_A.bed', 'insertions_A.bed' in subfolder A for individual 'A'.  if so, you run the scripts 'python2.7  path to/Scripts/merge_deletions.py -f deletions', you will got the combined bed files for each TE element and their host individual. 
Hope this will helpful!
